#' Recode teams names
#' 
#' @aliases do_recode_teams
#'
#' @description 
#' Some teams have different names, according to the sponsors, in different seasons.
#' This function collapses the names in order to have the same team name in the same
#' season and along the seasons. 
#' 
#' @usage 
#' do_recode_teams(competition, df_games)
#' 
#' @param competition String. Options are "ACB", "Euroleague", "Eurocup" and "DIA.
#' @param df_games Data frame with the games.
#' 
#' @note 
#' This function is not included in the package because as new games are played, 
#' the team names might change, so the user has to add the eventual new 
#' team name to this function to collapse it with the previous names 
#' the team received. So if the function belonged to the package, every 
#' time that the function is changed, the package should be again
#' submitted to CRAN and it doesn't make sense to submit new versions of 
#' the package just for one minor change. So it is suggested to download
#' this script, save it in the user working directory and change it manually.
#' It needs the dplyr and forcats packages.
#' 
#' @return 
#' Data frame.
#' 
#' @author 
#' Guillermo Vinue
#' 
#' @importFrom forcats fct_collapse
#'                  
#' @export

do_recode_teams <- function(competition, df_games){
  
  if (competition == "ACB") {
    df_games1 <- df_games %>%
      mutate(Team = fct_collapse(Team,
                                 Alicante = c("etosa alicante", "lucentum alicante", 
                                              "meridiano alicante", "proaguas costablanca"),
                                 Andorra = c("festina andorra", "morabanc andorra"),
                                 Baskonia = c("baskonia", "caja alava", "caja laboral", "laboral kutxa", 
                                              "laboral kutxa baskonia", "tau ceramica", "taugres",
                                              "tau cer&#225;mica", "taugres vitoria",
                                              "kirolbet baskonia", "tau cer&aacute;mica",
                                              "taugr&eacute;s"),
                                 Bilbao = c("bilbao basket", "bizkaia bilbao basket", "cajabilbao", 
                                            "dominion bilbao basket", "iurbentia bilbao basket", 
                                            "lagun aro bilbao basket", "retabet bilbao basket",
                                            "gescrap bizkaia", "gescrap bizkaia bilbao basket",
                                            "uxue bilbao basket"),
                                 Breogan = c("breogan caixa galicia", "breogan lugo", "breogan universidade", 
                                             "dyc breogan", "dyc lugo", "leche rio", "leche rio breogan",
                                             "cafes candelas breogan", "leche rio breog&aacute;n"),
                                 Burgos = c("san pablo burgos"),
                                 Caceres = c("caceres c.b.", "caceres cb", "c&aacute;ceres c.b."),
                                 Caja_Canarias = c("cajacanarias"),
                                 Caja_Madrid = c("cajamadrid"),
                                 Cantabria = c("caja cantabria", "cantabria lobos", "lobos caja cantabria"),
                                 Espanol = c("espanol juver", "gin mg sarria", "ifa espanol", "grupo ifa"),
                                 Estudiantes = c("adecco estudiantes", "asefa estudiantes", "estudiantes", 
                                                 "estudiantes argentaria", "estudiantes bose", 
                                                 "estudiantes caja postal", "estudiantes todagres", 
                                                 "mmt estudiantes", "movistar estudiantes", "estudiantes todag.",
                                                 "tuenti movil estudiantes", "estudiantes c.p."),
                                 FC_Barcelona = c("axa f.c. barcelona", "f.c. barcelona", 
                                                  "f.c. barcelona banca catalana", "barca lassa",
                                                  "fc barcelona b. catalana", "fc barcelona b.c.",
                                                  "fc barcelona", "fc barcelona lassa", "fc barcelona regal", 
                                                  "regal fc barcelona", "winterthur f.c. barcelona",
                                                  "regal barcelona", "regal f.c. barcelona", "barcelona"),
                                 Ferrol = c("c. baloncesto oar", "clesa ferrol", "oar ferrol", 
                                            "oar pescanova ferrol"),
                                 Fuenlabrada = c("alta gestion fuenlabrada", "ayuda en accion fuenlabrada", 
                                                 "baloncesto fuenlabrada", "j. pardo fuenla.", 
                                                 "jabones pardo fuenlabrada", "alta gesti&#211;n fuenlabrada",
                                                 "mad-croc fuenlabrada", "montakit fuenlabrada",
                                                 "ayuda en accia³n fuenlabrada", "ayuda en accion fuenla.",
                                                 "b. fuenlabrada", "mad-croc fue"),
                                 Gijon = c("cabitel gijon b.", "gijon baloncesto"),
                                 Girona = c("akasvayu girona", "casademont girona", "girona gavis", 
                                            "valvi girona"),
                                 Granada = c("cb granada", "c.b. granada", "coviran cervezas alhambra", 
                                             "coviran granada", "coviran sierra nevada granada", "granada", 
                                             "oximesa granada", "puleva baloncesto  granada", 
                                             "puleva baloncesto granada", "covir&aacute;n sierra nevada granada",
                                             "covir&aacute;n granada"),
                                 Gran_Canaria = c("auna", "auna g. canaria", "canarias telecom", "c.b. gran canaria", 
                                                  "claret las palmas", "kalise gran canaria", "gran canaria", 
                                                  "gran canaria 2014", "gran canaria grupo dunas", 
                                                  "herbalife gran canaria"),
                                 Granollers = c("bfi granollers", "cacaolat granollers",
                                                "granollers e.b.", "grupo ifa granollers", "cacaolat"),
                                 Guipuzcoa = c("bruesa gbc", "caja guipuzcoa", "gipuzkoa basket", 
                                               "lagun aro gbc", "retabet.es gbc", "delteco gbc"),
                                 Huelva = c("c.b. ciudad de huelva"),
                                 Huesca = c("argal huesca", "grupo agb huesca", "huesca magia", "huesca la magia", 
                                            "magia de huesca", "magia huesca", "somontano huesca"),
                                 Joventut = c("7up joventut", "divina seguros joventut", "dkv joventut", 
                                              "festina joventut", "fiatc joventut", "fiatc mutua joventut", 
                                              "joventut badalona", "marbella joventut",
                                              "montigala joventut", "pinturas bruguer badalona", "ram joventut", 
                                              "ram joventut badalona", "ron negrita joventut",
                                              "p.bruguer badalona", "r.negrita joventut"),
                                 Leon = c("b. leon caja espana", "baloncesto leon", "grupo begar leon", 
                                          "c.b. elosua leon", "elmar leon", "elosua leon", "leon caja espana"),
                                 Licor_43 = c("licor 43"),
                                 Lleida = c("caprabo lleida", "plus pujol lleida"),
                                 Lliria = c("club basket ferrys lliria", "ferrys lliria"),
                                 Manresa = c("assignia manresa", "basquet manresa", 
                                             "icl manresa", "la bruixa d'or", "la bruixa da´or", 
                                             "la bruixa d'or manresa", "ricoh manresa", 
                                             "suzuki manresa", "tdk manresa", "baxi manresa"),
                                 Mayoral_Maristas = c("mayoral maristas"),
                                 Menorca = c("llanera menorca", "menorca basquet", "vivemenorca"),
                                 Murcia = c("c. baloncesto murcia", "c.b. juver murcia", "cb murcia", 
                                            "club baloncesto murcia",
                                            "c.b. murcia", "c.b. murcia artel", "juver murcia", 
                                            "polaris world cb murcia", "polaris world mur", 
                                            "recreativos orenes murcia", "ucam murcia", "ucam murcia cb", 
                                            "zumos juver murcia"),
                                 Obradoiro = c("caixa ourense", "coren orense", "blusens monbus", 
                                               "c. ourense baloncesto", "ourense xacobeo 99", 
                                               "rio natura monbus", "rio natura monbus obradoiro", 
                                               "xacobeo 99 ourense", "xacobeo blu:sens", "monbus obradoiro"),
                                 Real_Madrid = c("real madrid", "real madrid asegurator", 
                                                 "real madrid otaysa", "real madrid teka",
                                                 "real madrid aseg."),
                                 Salamanca = c("baloncesto salamanca"),
                                 Sevilla = c("baloncesto sevilla", "banca civica", "cajasol", 
                                             "real betis energia plus", "caja san fernando",
                                             "cajasol banca civica"),
                                 Tenerife = c("cb canarias", "iberostar tenerife", 
                                              "unelco tenerife", "tenerife n&ordm; 1"),
                                 Unicaja = c("caja ronda", "unicaja", "unicaja mayoral", 
                                             "unicaja polti", "unicaja ronda"),
                                 Valencia = c("pamesa c valencia", "pamesa ceramica", "pamesa valencia", 
                                              "power electronics valencia", "valencia basket", 
                                              "valencia basket club", "pamesa ceramica valencia"),
                                 Valladolid = c("blancos de rueda valladolid", "cb valladolid", 
                                                "forum filatelico",
                                                "forum filatelico valaldolid",  "forum filatelico valladolid", 
                                                "forum valladolid", "forum valladolid c.b.", 
                                                "grupo capitol valladolid", "grupo libro valladolid",
                                                "c. baloncesto valladolid", "forum filat&eacute;lico valaldolid"),
                                 Villalba = c("atletico madrid villalba", "bancobao villalba", 
                                              "bbv collado villalba", "bbv villalba", "c.b. collado villalba"),
                                 Zaragoza = c("amway zaragoza", "banco natwest zaragoza", 
                                              "cai zaragoza", "tecnyconta zaragoza",
                                              "b. natwest zaragoza", "b.natwest zaragoza")))  
  }
  
  
  if (competition == "Euroleague") {
    df_games1 <- df_games %>%
      mutate(Team = fct_collapse(Team,
                                 AEK_Atenas = c("aek athens"),
                                 Air_Avellino = c("air avellino"),
                                 Alba_Berlin = c("alba berlin"), 
                                 Aris = c("aris tt bank"),
                                 Asseco_Prokom = c("asseco prokom", "asseco prokom gdynia",
                                                   "prokom trefl sopot"), 
                                 Asvel = c("asvel basket"),
                                 Bamberg = c("brose bamberg", "brose baskets", "brose baskets bamberg",
                                             "ghp bamberg"), 
                                 Baskonia = c("tau ceramica", "baskonia vitoria gasteiz",
                                              "caja laboral", "caja laboral vitoria",
                                              "laboral kutxa vitoria", "laboral kutxa vitoria gasteiz",
                                              "kirolbet baskonia vitoria-gasteiz"), 
                                 Bayern_Munich = c("fc bayern munich"),
                                 Benetton = c("benetton basket"),
                                 Besiktas = c("besiktas jk istanbul"),
                                 Bilbao = c("gescrap bilbao basket"), 
                                 Bolonia_Virtus = c("virtus bologna", "virtus vidivici", "kinder bologna"),
                                 Bolonia_Fortitudo = c("skipper bologna", "climamio bologna", "paf bologna"),
                                 Buducnost = c("kk buducnost", "buducnost voli podgorica"), 
                                 Cantu = c("mapooro cantu", "bennet cantu"),
                                 Cedevita = c("cedevita zagreb"),
                                 Chalon = c("elan chalon-sur-saone"),
                                 Charleroi = c("spirou charleroi", "spirou basket",
                                               "region wallone spirou charleroi", 
                                               "belgacom spirou charleroi"),
                                 Cholet = c("cholet basket"),
                                 Cibona = c("cibona", "cibona vip", "cibona zagreb"), 
                                 Crvena_Zvezda_Belgrade = c("crvena zvezda mts belgrade", 
                                                            "crvena zvezda telekom belgrade"),
                                 CSKA = c("cska moscow"),
                                 Darussafaka = c("darussafaka dogus istanbul",
                                                 "darussafaka tekfen istanbul"), 
                                 Efes_Pilsen = c("efes pilsen", "efes pilsen istanbul", "anadolu efes istanbul"),
                                 Estudiantes = c("adecco estudiantes"),
                                 FC_Barcelona = c("axa fc barcelona", "fc barcelona", "fc barcelona lassa",
                                                  "fc barcelona regal", "regal barcelona", "regal fc barcelona",
                                                  "winterthur fc barcelona"),
                                 Fenerbahce = c("fenerbahce dogus istanbul", "fenerbahce istanbul",
                                                "fenerbahce ulker", "fenerbahce ulker istanbul", "ulker",
                                                "fenerbahce beko istanbul"),
                                 Frankfort = c("opel skyliners"),
                                 Galatasaray = c("galatasaray liv hospital istanbul", 
                                                 "galatasaray medical park", "galatasaray odeabank istanbul"), 
                                 Gran_Canaria = c("herbalife gran canaria"),
                                 Hapoel_Jerusalem = c("hapoel jerusalem"), 
                                 Idea_Slask = c("idea slask"),
                                 Joventut = c("dkv joventut"),
                                 Karsiyaka = c("pinar karsiyaka izmir"),
                                 Khimki = c("bc khimki", "khimki moscow region"),
                                 Kiev = c("budivelnik kiev"),
                                 Kuban = c("lokomotiv kuban krasnodar"),
                                 Le_Mans = c("le mans"),
                                 Lietuvos_Rytas = c("lietuvos rytas", "lietuvos rytas vilnius"),
                                 Limoges = c("limoges csp"),
                                 London = c("haribo london towers", "kinder london towers"),
                                 Lugano = c("lugano snakes"),
                                 Maccabi = c("maccabi electra", "maccabi electra tel aviv", 
                                             "maccabi elite", "maccabi fox tel aviv"), 
                                 Maroussi = c("maroussi bc"),
                                 Milan = c("aj milano", "armani jeans  milano", "armani jeans milano", 
                                           "ax armani exchange olimpia milan", "ea7 emporio armani milan",
                                           "ea7 emporio armani"),
                                 Nancy = c("sluc nancy"),
                                 Nanterre = c("jsf nanterre"),
                                 Napoli = c("eldo napoli"),
                                 Neptunas_Klaipeda = c("neptunas klaipeda"), 
                                 Nizhny = c("nizhny novgorod"), 
                                 Novo_Mesto = c("krka novo mesto"),
                                 Oldenburg = c("ewe baskets"),
                                 Olimpija_Ljubljana = c("union olimpija", "union olimpija ljubljana"),
                                 Olympiakos = c("olympiakos", "olympiacos piraeus", "olympiacos"),
                                 Oostende = c("telindus oostende"),
                                 Orleans = c("entente orleanaise"),
                                 Ovarense = c("ovarense aerosoles"),
                                 Panathinaikos = c("panathinaikos", "panathinaikos athens", 
                                                   "panathinaikos superfoods athens",
                                                   "panathinaikos opap athens"),
                                 Panionios = c("panionios on telecoms"),
                                 Paok = c("paok bc"),
                                 Partizan = c("partizan igokea", "partizan mt:s belgrade",
                                              "partizan nis belgrade", "partizan"),
                                 Pau_Orthez = c("pau-orthez"),
                                 Peristeri = c("peristeri"), 
                                 Pesaro = c("scavolini pesaro"),
                                 Rhein_Energie = c("rheinenergie"),
                                 Real_Madrid = c("real madrid"),
                                 Roanne = c("chorale roanne"),
                                 Roma = c("lottomatica roma"),
                                 Sassari = c("dinamo banco di sardegna sassari"),
                                 Siena = c("montepaschi siena"),
                                 St_Petersburg_Lions = c("st. petersburg lions"),
                                 Strasbourg = c("strasbourg"),
                                 Unicaja = c("unicaja", "unicaja malaga"),
                                 Unics_Kazan = c("unics kazan"),
                                 Ural_Great = c("ural great"),
                                 Valencia = c("pamesa valencia", "power electronics valencia", 
                                              "valencia basket"),
                                 Verona = c("muller verona"),
                                 Zadar = c("kk zadar"),
                                 KK_Zagreb = c("kk zagreb"),
                                 Zalgiris = c("zalgiris", "zalgiris kaunas"),
                                 Zenit = c("dynamo moscow"),
                                 Zielona_Gora = c("stelmet zielona gora"),
                                 Zgorzelec = c("pge turow zgorzelec")))  
  }
  
  
  if (competition == "Eurocup") {
    df_games1 <- df_games %>%
      mutate(Team = fct_collapse(Team,
                                 AEK_Atenas = c("aek athens"),
                                 Alba_Berlin = c("alba berlin"),
                                 Alba_Fehervar = c("alba fehervar"),
                                 Aleksandrovac = c("igokea aleksandrovac"),
                                 Alicante = c("etosa alicante"),
                                 Amsterdam = c("demon astronauts", "ricoh astronauts"),
                                 Andorra = c("morabanc andorra"),
                                 Ankara = c("aykon ted ankara kolejliler"),
                                 Antwerp = c("antwerp giants"),
                                 Aris = c("aris bsa", "aris bsa 2003", "aris egnatia bank",
                                          "aris thessaloniki"),
                                 Artland_Dragons = c("artland dragons", "artland dragons quakenbrueck"),
                                 Asseco_Prokom = c("trefl sopot", "prokom trefl sopot", "arka gdynia"),
                                 Asvel = c("adecco asvel", "asvel lyon villeurbanne",
                                           "asvel villeurbanne", "asvel villeurbanne lyon",
                                           "asvel basket", "ldlc asvel villeurbanne"),
                                 Bamberg = c("brose baskets", "brose baskets bamberg", "ghp bamberg"),
                                 Banvit = c("banvit bandirma", "banvit bk", "banvit bk bandirma"),
                                 Bar = c("mornar bar"),
                                 Bayern_Munich = c("fc bayern munich"),
                                 Bc_Fmp = c("bc fmp", "bc fmp zeleznik"),
                                 Benfica = c("sport lisboa e benfica"),
                                 Besiktas = c("besiktas c.turka", "besiktas cola turka", "besiktas colaturka",
                                              "besiktas integral forex istanbul", "besiktas jk colaturka",
                                              "besiktas sompo japan istanbul"),
                                 Brescia = c("germani brescia leonessa"),
                                 Biella = c("lauretana biella"),
                                 Bilbao = c("uxue bilbao basket", "bilbao basket", 
                                            "bizkaia bilbao b", "dominion bilbao basket",
                                            "iurbentia bilbao", "retabet bilbao basket"),
                                 Bolonia_Virtus = c("wwf virtus bologna"),
                                 Bolonia_Fortitudo = c("fortitudo bologna", "beghelli bologna"),
                                 Bonn = c("telekom bonn", "telekom baskets bonn"),
                                 Bosna = c("kk bosna"),
                                 Braunschweig = c("bs energy braunschweig"),
                                 Bree = c("euphony basket bree"),
                                 Brighton = c("brighton bears"),
                                 Brindisi = c("enel basket brindisi"),
                                 Buducnost = c("buducnost m:tel", "buducnost voli podgorica",
                                               "kk buducnost", "kk buducnost voli"),
                                 Bursa = c("tofas bursa"),
                                 Cantu = c("vertical vision cantu", "foxtown cantu", "bennet cantu"),
                                 Caserta = c("pepsi caserta"),
                                 Cedevita = c("cedevita", "cedevita zagreb"),
                                 Cibona = c("cibona zagreb", "kk cibona", "kk cibona zagreb"),
                                 Chalon = c("elan chalon", "elan chalon sur saone"),
                                 Charleroi = c("belgacom spirou basket", "belgacom spirou charleroi",
                                               "proximus spirou charleroi", "spirou basket",
                                               "spirou charleroi"),
                                 Cholet = c("cholet basket"),
                                 Crvena_Zvezda_Belgrade = c("crvena zvezda", "crvena zvezda telekom belgrade",
                                                            "crvena zvezda mts belgrade"),
                                 Darussafaka = c("darussafaka istanbul"),
                                 Debreceni = c("debreceni vadkakasok"),
                                 Dijon = c("jda dijon"),
                                 Donetsk = c("bc donetsk"),
                                 Eiffeltowers = c("eiffeltowers", "eiffeltowers den bosch"),
                                 Estudiantes = c("adecco estudiantes", "asefa estudiantes"),
                                 Fmp_Zeleknik = c("fmp", "bc reflex"), 
                                 Frankfort = c("opel skyliners", "fraport skyliners",
                                               "d. bank skyliners", "deutsche bank skyliners",
                                               "fraport skyliners frankfurt"),
                                 Fribourg = c("benetton fribourg"),
                                 Fuenlabrada = c("montakit fuenlabrada", "jabones pardo fuenlabrada"),
                                 Galatasaray = c("galatasaray cafe crown", "galatasaray cc",                   
                                                 "galatasaray medical park", "galatasaray odeabank istanbul",
                                                 "galatasaray istanbul"),
                                 Girona = c("akasvayu girona"),
                                 Gmunden = c("swans gmunden"),
                                 Goettingen = c("bg goettingen"),
                                 Gran_Canaria = c("auna gran canaria", "gran canaria",
                                                  "gran canaria 2014", "herbalife gran canaria",
                                                  "herbalife gran canaria las palmas",
                                                  "kalise g. canaria", "kalise gran canaria"),
                                 Gravelines = c("bcm gravelines", "bcm gravelines dunkerque"),
                                 Groningen = c("mpc capitals groningen", "gasterra flames",
                                               "hanzevast capitals"),
                                 Guildford = c("guildford heat"),
                                 Hapoel_Jerusalem = c("hapoel bank yahav jerusalem", "hapoel galil elyon",
                                                      "hapoel gilboa galil", "hapoel jerusalem", 
                                                      "hapoel migdal", "hapoel migdal jerusalem"),
                                 Hemofarm = c("hemofarm", "hemofarm stada"),
                                 Herzlia = c("bnei hasharon"),
                                 Ionikos = c("ionikos nf egnatia bank"),
                                 Joventut = c("dkv joventut"),
                                 Kapfenberg = c("superfund kapfenberg"),
                                 Karsiyaka = c("pinar karsiyaka izmir"),
                                 Khimki = c("bc khimki", "khimik yuzhne", "khimki", "khimki moscow region"),
                                 Kiev = c("bc budivelnik kiev", "bc kyiv",
                                          "budivelnik", "budivelnik kiev"),
                                 KK_Atlas = c("kk atlas belgrade"),
                                 Kragujevac = c("radnicki kragujevac"),
                                 Kuban = c("lokomotiv kuban", "lokomotiv kuban krasnodar",
                                           "pbc lokomotiv kuban krasnodar"),
                                 Lasko = c("kk pivovarna lasko"),
                                 Le_Havre = c("stb le havre"),
                                 Le_Mans = c("le mans", "le mans sarthe basket"),
                                 Liege = c("liege"),
                                 Lietuvos_Rytas = c("lietuvos rytas", "lietuvos rytas vilnius",
                                                    "rytas vilnius"),
                                 Limoges = c("limoges csp"),
                                 Lleida = c("caprabo lleida"),
                                 Loimaa = c("bisons loimaa"),
                                 Ludwigsburg = c("ludwigsburg", "mhp riesen ludwigsburg"),
                                 Lukoil = c("lukoil academic", "lukoil academic sofia"),
                                 Maccabi = c("maccabi fox tel aviv"),
                                 Maccabi_Haifa = c("maccabi haifa bazan"),
                                 Makedonikos = c("makedonikos bc"),
                                 Mariupol = c("azovmash mariupol", "bc azovmash", "bc azovmash mariupol"),
                                 Maroussi = c("maroussi costa coffee", "maroussi honda"),
                                 Monaco = c("as monaco"),
                                 Mons = c("belfius mons hainaut", "belfius mons-hainaut", "dexia mons"),
                                 Milan = c("breil milano", "ea7 emporio armani milan"),
                                 Murcia = c("ucam murcia"),
                                 Nancy = c("nancy", "sluc nancy"),
                                 Napoli = c("pompea napoli"),
                                 Nanterre = c("jsf nanterre"),
                                 Neptunas_Klaipeda = c("neptunas klaipeda"),
                                 Nizhny = c("nizhny novgorod"),
                                 Novo_Mesto = c("krka novo mesto"),
                                 Nymburk = c("cez basketball nymburk", "cez nymburk"),
                                 Oldenburg = c("ewe baskets", "ewe baskets oldenburg"),
                                 Olimpija_Ljubljana = c("union olimpija ljubljana"),
                                 Orleans = c("orleans loiret basket"),
                                 Oostende = c("telindus oostende", "telenet oostende", 
                                              "telenet ostend", "bc oostende", "oostende"),
                                 Ovarense = c("ovarense aerosoles"),
                                 Panellinios = c("panellinios bc", "panellinios gs", "panellinios opap"),
                                 Panevezys = c("lietkabelis panevezys"),
                                 Panionios = c("panionios athens", "panionios bc athens",
                                               "panionios forthnet", "panionios on telecoms"),
                                 Pao_Orthez = c("pau-orthez"),
                                 Paok = c("paok", "paok bc", "paok thessaloniki"),
                                 Paris = c("paris levallois", "levallois metropolitans"),
                                 Partizan = c("partizan nis belgrade"),
                                 Pepinster = c("royal bc verviers pepinster"),
                                 Ploiesti = c("csu asesoft", "csu asesoft ploiesti"),
                                 Prienai = c("bc prienai", "bc rudupis"),
                                 Real_Madrid = c("real madrid"),
                                 Red_star = c("cb red star", "red star"),
                                 Reggio_Emilia = c("grissin bon reggio emilia",
                                                   "landi renzo reggio emilia"),
                                 Rhein_Energie_Koln = c("rheinenergie cologne", "k&#246;ln 99ers"),
                                 Riga = c("ask riga", "vef riga", "barons/lmt riga"),
                                 Roanne = c("chorale roanne"),
                                 Roma = c("virtus roma", "virtus rome"),
                                 Roseto = c("eurocellulari roseto"),
                                 Samara = c("krasnye krylia"),
                                 Sassari = c("dinamo banco di sardegna sassari"),
                                 Saratow = c("avtodor saratov"),
                                 Sevilla = c("baloncesto seville", "cajasol sevilla", "cajasol seville"),
                                 Siauliai = c("bc siauliai", "siauliai"),
                                 Siena = c("montepaschi", "montepaschi siena"),
                                 Sintra = c("queluz sintra pm"),
                                 Skopje = c("mzt skopje aerodrom"),
                                 Spartak_St_Petersburg = c("spartak saint petersburg", 
                                                           "spartak spb", "spartak st. petersburg"),
                                 Split = c("split croatia insurance"),
                                 Steaua_Bucharest = c("steaua csm eximbank bucharest"),
                                 Strasbourg = c("strasbourg"),
                                 Szolnok = c("szolnoki olaj"),
                                 Tallin = c("bc kalev/cramo", "kalev cramo tallinn"),
                                 Teramo = c("bancatercas teramo"),
                                 Trabzonspor = c("trabzonspor medical park"),
                                 Trento = c("dolomiti energia trento"),
                                 Treviso = c("benetton basket", "benetton bwin", "benetton tamoil"),
                                 Trieste = c("generali group trieste"),
                                 Turin = c("fiat turin"),
                                 Turk_Telekom = c("turk telekom", "turk telekom ankara"),
                                 Udine = c("snaidero udine"),
                                 Ulm = c("ratiopharm ulm"),
                                 Unicaja = c("unicaja malaga"),
                                 Unics_Kazan = c("unics", "unics kazan"),
                                 Ural_Great = c("ural great perm"),
                                 Valencia = c("valencia basket", "valencia basket club",
                                              "pamesa valencia", "power electronics"),
                                 Varese = c("metis varese", "cimberio varese", "corimec varese"),
                                 Venice = c("umana reyer venice"),
                                 Ventspils = c("ventspils", "bk ventspils"),
                                 Volgograd = c("krasny oktyabr volgograd"),
                                 Wloclawek = c("anwil wloclawek"),
                                 Wroclaw = c("asco slask wroclaw", "wtk anwil wloclawek",
                                             "deichmann slask wroclaw"),
                                 Wurzburg = c("s.oliver baskets wurzburg"),
                                 Zadar = c("zadar", "kk zadar"),
                                 KK_Zagreb = c("kk zagreb"),
                                 Zaragoza = c("cai zaragoza"),
                                 Zenit = c("zenit st petersburg", "triumph lyubertsy", 
                                           "dynamo moscow", "bc triumph", "bc triumph lyubertsy"),
                                 Zielona_Gora = c("stelmet zielona gora"),
                                 Zgorzelec = c("pge tur&#243;w zgorzelec", "pge turow", "pge turow zgorzelec")))  
  }
      
  
  if (competition == "DIA") {
    df_games1 <- df_games %>%
      mutate(Team = fct_collapse(Team,
                                 Andalucia_Aifos = c("Andalucia - Aifos", "Andalucia Aifos",
                                                     "Andalucia Solo Hay Una"),
                                 Araski = c("Lacturale Araski", "Lacturale Art Araski"),
                                 Badajoz = c("Extremadura Dato"),
                                 Baloncesto_Alcala = c("Baloncesto Alcala"),
                                 Bembibre = c("Embutidos Pajariel Bembibre Pd", "C.b. Bembibre Pdm"),
                                 Bizkaia = c("Gernika Bizkaia", "Lointek Gernika Bizkaia", "Bizkaia Gdko"),
                                 Burgos = c("Arranz - Jopisa Burgos", "Arranz Acinas", "Arranz-Jopisa Burgos",
                                            "B. Ciudad De Burgos", "Baloncesto Ciudad De Burgos",
                                            "Beroil - Ciudad De Burgos", "Ciudad De Burgos",
                                            "C.b. Ciudad De Burgos", "Tizona Burgos", "Jopisa Ciudad De Burgos"),
                                 Campus_Promete = c("Campus Promete", "Campus Promete Lf1"),
                                 Canal_Isabel_II = c("Canal Isabel Ii"),
                                 Canarias = c("Caja Rural De Canarias", "Cajacanarias"), 
                                 Canoe = c("Real Canoe N.c.", "Real Canoe", "Motiva Real Canoe N.c.",
                                           "T. Roma´S Canoe"),
                                 CBN = c("C.b.n.", "Cbn"),
                                 Celta = c("R.club Celta Banco Simeon", "Rc Celta Baloncesto", "Rc Celta Indepo",
                                           "Real Club Celta Banco Simeon", "Real Club Celta Indepo", "Real Club Celta Vigourban",
                                           "Banco Simeon"),
                                 Conquero = c("C.b. Conquero Huelva Wagen", "Club Baloncesto Conquero",
                                              "Toyota Recreativo  Conquero"),
                                 Cortegada = c("A.d. Cortegada", "Cortegada", "Cortegada-Grupo 10",
                                               "Extrugasa Cocinas Carballo", "Extrugasa Muebles Carballo",
                                               "Extrugasa"),
                                 CREF = c("C.r.e.f. ¡Hola!"),
                                 Ensino = c("Ensino Yaya Maria", "Yaya Maria Breogan", "Yaya María Porta Xi",
                                            "C.d. Ensino", "Ensino"),
                                 Estudiantes = c("Asefa Estudiantes", "Movistar Estudiantes",
                                                 "Usp Ceu - Adecco Estudiantes", "Usp-Ceu Mmt Estudiantes"),
                                 Extremadura = c("C.b. Al-Qázeres Extremadura", "Nissan  Al-Qázeres Extremadura"),
                                 FC_Barcelona = c("Barcelona Bc.universitari", "Universitat De Barcelona", 
                                                  "Universitat De Barcelona - F.c", "Universitat De Barcelona B.f.",
                                                  "Ub F.c Barcelona", "Universitari"), 
                                 Ferrol = c("Star Center-Uni Ferrol", "Universitario De Ferrol"),
                                 Getafe = c("Pool Getafe"),
                                 Gipuzkoa = c("Idk Gipuzkoa", "Idk Gipuzkoa Upv", "Gipuzkoa Upv"),
                                 Girona = c("Argon Uni Girona", "Spar Unigirona",
                                            "Spar Citylift Girona", "Girona Fc"),
                                 Godella = c("Popular Basquet Godella", "Godella"),
                                 Gran_Canaria = c("Sandra G. Canaria", "Sandra Gran Canaria",
                                                  "Gran Canaria", "Gran Canaria 2014 ", 
                                                  "Gran Canaria La Caja De Canari", "Spar Gran Canaria",
                                                  "G Canaria 2014 Caja De Canari", "Gcanaria 2014 Caja De Canari"),
                                 Hondarribia = c("Hondarribia - Irún", "Hondarribia-Irún"),
                                 Hospitalet = c("Bf Hospitalet"),
                                 La_Seu = c("Cadi - Icg Software", "Cadi La Seu", "Cadi La Seu D´Urgell"),
                                 Leon = c("Acis Incosa Leon", "Acis-Sufi Leon",
                                          "Club Baloncesto San José", "Cb Feve San José"),
                                 Linares = c("Cajasur Linares"),
                                 Mendibil = c("P.c. Mendibil"),
                                 Obenasa = c("Unb Obenasa", "Unb Obenasa Lacturale"),
                                 Olesa = c("C.b. Olesa", "C.b. Olesa - Espanyol"),
                                 Rioja = c("Añares Rioja Isb"),
                                 Rivas = c("Rivas Ecopolis", "Rivas Ecópolis", "Rivas Futura"),
                                 Rosa_Lima = c("Cb.sta.rosa De Lima Horta", "C.b. Sta. Rosa De Lima"),
                                 Salamanca = c("Halcon Viajes", "Salamanca Halcon Viajes",
                                               "Perfumerias Avenida"),
                                 Sant_Adria = c("Snatt´S Femení Sant Adriá"),
                                 Santa_Eulalia = c("Ebe Promociones Santa Eulaliai", 
                                                   "Ebe Promociones-Pdv Sta.eulali",
                                                   "C.b. Puig D`En Valls Santa Eul",
                                                   "Palacio De Congresos De Ibiza",
                                                   "Ebe Ibiza-Pdv"),
                                 Soller = c("Sóller Bon Día!", "Soller Joventut Mariana"),
                                 Tenerife = c("Symel Tenerife"),
                                 Tres_Cantos = c("Femenino Tres Cantos", "Tres Cantos"), 
                                 Universidad_Oviedo = c("A.d.universidad De Oviedo",
                                                        "Univ. Oviedo", "Universidad De Oviedo"),
                                 Valencia = c("C. Ros Casares Valencia", "Ciudad Ros Casares", 
                                              "Ciudad Ros Casares Valencia",
                                              "Ros Casares", "Ros Casares Valencia"),
                                 Zamarat = c("Zamarat", "Quesos El Pastor", "Quesos El Pastor De La Polvoro",
                                             "Tintos De Toro Caja Rural", "Caja Rural Tintos De Toro"),
                                 Vetusta_Oviedo = c("Vetusta Oviedo"), 
                                 Zamora = c("Alimentos De Zamora"),
                                 Zaragoza = c("Mann Filter Zaragoza", "Mann-Filter",
                                              "Filtros Mann Zaragoza", "Basket Zaragoza")))
  }
  
  
  return(df_games1)
}