---
title: Buscador de estadísticas de baloncesto / Search engine of basketball statistics.
author: Guillermo Vinué
date: '2019-06-24'
slug: buscador-datos-baloncesto
categories: ["R"]
tags: ["buscador", "datos"]
runtime: shiny
---

```{r tables, include=FALSE,message=FALSE}
knitr::opts_knit$set(bookdown.internal.label = FALSE)
```

<br>

Este artículo quiere informar de una aplicación interactiva que he desarrollado en forma de buscador de las estadísticas conseguidas por cualquier jugador contra un determinado equipo. Los datos disponibles proceden de la ACB, la Euroliga y la Eurocup. La app está disponible en español y en inglés y necesita unos segundos para cargar todos los datos.

Los pasos a seguir son los siguientes:

1. Elegir una liga y un formato de competición (liga regular, playoffs, etc).
2. Elegir un jugador, un equipo y el tipo de estadísticas a calcular (totales o promedio).

Las tablas resultantes muestran la información biográfica básica del jugador, sus estadísticas totales o promedio y en cada uno de sus partidos contra el rival seleccionado. La pestaña "Información" contiene un enlace a un documento con el significado de las abreviaturas de las estadísticas.

Cualquier persona interesada en esta aplicación, puede contactarme en el correo electrónico indicado al final del documento.

**IN ENGLISH:**

This reports aims to inform about an interactive app that I have developed as a search engine of the statistics achieved by any player against a certain rival. The data come from the Spanish first division league (ACB), Euroleague and Eurocup. The app is available in Spanish and English and needs a few seconds to load all the data.

The procedure is as follows:

1. Choose a league and a round of competition (regular season, playoffs, etc).
2. Choose a player, a team and the type of the stats to be computed (total or average).

The resulting tables show the basic player's biographic data, the total or average stats and each game stats. The "Information" tab contains a link to a document with the meaning of the abbreviations for the statistics.

Anyone interested in this app can contact me at the email indicated below.

## Datos y software (Data and software)

El material para reproducir este estudio se puede descargar en [este enlace.](https://github.com/guivivi/sportsandvisualdata/tree/master/content/post/data_scripts)

**IN ENGLISH:**

The material to reproduce this analysis is available at [this link.](https://github.com/guivivi/sportsandvisualdata/tree/master/content/post/data_scripts)

*Guillermo Vinué*\
*guillermovinue@gmail.com*